# The location to use for storing cached Git repos
:cachedir: '/var/cache/r10k'

# A list of git repositories to create
:sources:
  # This will clone the git repository and instantiate an environment per
  # branch in /etc/puppet/environments
  :my-org:
    remote: 'https://github.com/Orange-OpenSource/opnfv-r10k.git'
    basedir: '/etc/puppet/environments'
