---
inherit_from: ../.rubocop.yml

# rspec expectations look like == in void context
Void:
  Enabled: false

# an expectation of nil would look like foo.should == nil
NilComparison:
  Enabled: false

# Cop doesn't like {} used for multi-line blocks, but it's common for expect { }.to
Blocks:
  Enabled: false
