domains: "infra.opensteak.fr"
media: "Ubuntu mirror"
environments: "production"
operatingsystems: "Ubuntu 14.04 Cloud"
subnets: "Admin"
compute_profiles: "Test"
smart_proxies: "foreman.infra.opensteak.fr"
ptables: "Preseed default"
architectures: "x86_64"

operatingSystemsList:
 Ubuntu 14.04.1 LTS:
  name: "Ubuntu"
  description: "Ubuntu 14.04.1 LTS"
  major: "14"
  minor: "04"
  family: "Debian"
  release_name: "trusty"
  password_hash: "MD5"
  templates:
   - Preseed default
   - Preseed default PXELinux
   - Preseed default finish
  media:
   - Ubuntu mirror
  ptables:
   - Preseed default
 Ubuntu 14.04 Cloud:
  name: "Ubuntu14.04Cloud"
  description: "Ubuntu 14.04 Cloud"
  major: "14"
  minor: "04"
  family: "Debian"
  release_name: "trusty"
  password_hash: "MD5"
  templates:
   - Preseed default
   - Preseed default user data
  media:
   - Ubuntu mirror
  ptables:
   - Preseed default

configTemplatesList:
 Preseed default: "foreman/provisioning_templates/preseed_default.tpl"
 Preseed default finish: "foreman/provisioning_templates/preseed_default_finish.tpl"
 Preseed default PXELinux: "foreman/provisioning_templates/preseed_default_pxelinux.tpl"

hostgroupTop:
 name: 'test'
 classes:
 - "ntp"
 subnet: "Admin"
 params:
  password: 'toto'
hostgroupsList:
 hostgroupController:
  name: 'controller'
  classes:
   - "opensteak::base-network"
   - "opensteak::libvirt"
  params:
   foreman_sshkey: 'xxxx'
 hostgroupControllerVM:
  name: 'controller_VM'
  classes:
   - "opensteak::apt"
  params:
   foreman_sshkey: 'xxxx'
   password: 'toto'
 hostgroupCompute:
  name: 'compute'
  classes:
   - "opensteak::neutron-compute"
   - "opensteak::nova-compute"

subnetsList:
 Admin:
  domain: 'infra.opensteak.fr'
  shared: False
  data:
   network: "192.168.1.0"
   mask: "255.255.255.0"
   vlanid:
   gateway: "192.168.1.1"
   dns_primary: "192.168.1.2"
   from: "192.168.1.20"
   to: "192.168.1.170"
   ipam: "DHCP"
   boot_mode: "DHCP"
 Storage:
  domain: 'storage.opensteak.fr'
  shared: False
  data:
   network: "192.168.0.0"
   mask: "255.255.255.0"
   vlanid:
   from: "192.168.0.20"
   to: "192.168.0.170"
   ipam: "DHCP"
   boot_mode: "DHCP"
 VM:
  domain: 'vm.storage.opensteak.fr'
  shared: False
  data:
   network: "192.168.2.0"
   mask: "255.255.255.0"
   vlanid:
   from: "192.168.2.20"
   to: "192.168.2.170"
   ipam: "DHCP"
   boot_mode: "DHCP"

foreman:
 ip: "192.168.1.4"
 admin: "admin"
 password: "B1ng0!42"
 cpu: "2"
 ram: "2097152"
 iso: "trusty-server-cloudimg-amd64-disk1.img"
 disksize: "5G"
 force: True
 dns: "8.8.8.8"
 bridge: "virbr0"
 bridge_type: "openvswitch"
 classes:
  "opensteak::dhcp":
   dnsdomain: #Build with the other parameters
   interfaces:
    - "eth0"
    - "eth1"
    - "eth2"
   # We remove pools for the foreman 1.7, see bug 9240 corrected for 1.8.1
   # pools: #Build with the other parameters

controllersList:
 controller1:
  controllerName: 'controller1.infra.opensteak.fr'
  operatingSystem: "Ubuntu 14.04.1 LTS"
  macAddress: '40:f2:e9:2a:30:3b'
  password: "opnfv123"
  ipmiMacAddress: '40:f2:e9:2a:30:3e'
  impiIpAddress: "192.168.1.198"
  impiUser: 'user'
  impiPassword: "B1ng0!"
  params:
   ovs_config:
    - "br-adm:em3:dhcp"
    - "br-vm:em5:dhcp"
    - "br-ex:em2:none"
 # controller2:
  # controllerName: 'controller2.infra.opensteak.fr'
  # operatingSystem: "Ubuntu 14.04.1 LTS"
  # macAddress: '00:1a:64:c8:a9:7c'
  # password: "opnfv123"
  # ipmiMacAddress: '00:1a:64:cc:66:4d'
  # impiIpAddress: "192.168.1.194"
  # impiUser: 'user'
  # impiPassword: "B1ng0"
 # controller3:
  # controllerName: 'controller3.infra.opensteak.fr'
  # operatingSystem: "Ubuntu 14.04.1 LTS"
  # macAddress: 'a0:36:9f:4e:90:96'
  # password: "opnfv123"
  # ipmiMacAddress: '00:1a:64:cc:66:3d'
  # impiIpAddress: "192.168.1.192"
  # impiUser: 'user'
  # impiPassword: "B1ng0"
