nginx::nginx_vhosts:
  "keystone.%{hiera('domain')}":
     listen_port: 5000
     proxy: "http://keystone.%{hiera('domain')}:5000"
  "glance.%{hiera('domain')}":
     listen_port: 9292
     proxy: "http://glance.%{hiera('domain')}:9292"
  "nova.%{hiera('domain')}":
     listen_port: 8774
     proxy: "http://nova.%{hiera('domain')}:8774"
  "neutron.%{hiera('domain')}":
     listen_port: 9696
     proxy: "http://neutron.%{hiera('domain')}:9696"
  "cinder.%{hiera('domain')}":
     listen_port: 8776
     proxy: "http://cinder.%{hiera('domain')}:8776"
  "%{hiera('domain')}":
     listen_port: 80
     proxy: "http://horizon.%{hiera('domain')}"
  "%{hiera('domain')}":
     listen_port: 443
     ssl: true
     ssl_cert: "/var/lib/puppet/ssl/certs/proxy.%{hiera('domain')}.pem"
     ssl_key: "/var/lib/puppet/ssl/private_keys/proxy.%{hiera('domain')}.pem"
     proxy: "http://horizon.%{hiera('domain')}"
     proxy_redirect: "http://stack.opensteak.fr /"

