nginx::nginx_vhosts:
  "keystone.stack.%{hiera('domain')}":
     listen_port: 5000
     proxy: "http://keystone.stack.%{hiera('domain')}:5000"
  "glance.stack.%{hiera('domain')}":
     listen_port: 9292
     proxy: "http://glance.stack.%{hiera('domain')}:9292"
  "nova.stack.%{hiera('domain')}":
     listen_port: 8774
     proxy: "http://nova.stack.%{hiera('domain')}:8774"
  "neutron.stack.%{hiera('domain')}":
     listen_port: 9696
     proxy: "http://neutron.stack.%{hiera('domain')}:9696"
  "cinder.stack.%{hiera('domain')}":
     listen_port: 8776
     proxy: "http://cinder.stack.%{hiera('domain')}:8776"
  "stack.%{hiera('domain')}":
     listen_port: 80
     proxy: "http://horizon.stack.%{hiera('domain')}"
